const content = {
  en: {
    navProducts: "Products",
    navHome: "Home & Living",
    navCleaning: "Cleaning",
    navIndustrial: "Industrial",
    navPartners: "Partners",
    navProcess: "Process",
    navMarkets: "Markets",
    navProforma: "Create Proforma",
    navCustoms: "Customs",
    navB2B: "B2B Portal Login",
    headerCta: "Get Quote",
    installAppCta: "App",
    installPanelTitle: "Sidya Global app",
    installPanelCopy: "Open sidyaglobal.com on Android Chrome or iPhone Safari to add the site to your home screen.",
    installAndroid: "Open in Chrome, tap App, and confirm the install prompt.",
    installIos: "Open in Safari, tap Share, then choose Add to Home Screen.",
    installOpenSite: "Open sidyaglobal.com",
    installAppleNote: "iPhone does not allow automatic app downloads from a website; use Safari's Add to Home Screen option.",
    installAlreadyInstalled: "Sidya Global is already opening as an app window on this device.",
    installStarted: "App installation has started.",
    installCancelled: "App installation was cancelled.",
    installIosFallback: "On iPhone, open this site in Safari, tap Share, then choose Add to Home Screen.",
    installAndroidFallback: "If Android Chrome does not show the install prompt, open the browser menu and choose Install app or Add to Home screen.",
    exchangeTitle: "Current TCMB rates",
    exchangeLoading: "Loading...",
    exchangeUpdated: "Updated",
    exchangeChecked: "Checked",
    exchangeDataDate: "TCMB data",
    exchangeUnavailable: "Rates could not be loaded",
    heroEyebrow: "Cleaning â€¢ Industrial â€¢ Home & Living â€¢ Health â€¢ Personal Care",
    heroTitle: "Your Trusted Gateway to Reliable Products from TÃ¼rkiye",
    heroCopy:
      "Sidya Global helps international buyers source quality products from trusted Turkish suppliers â€” quickly, transparently, and professionally.",
    heroPrimary: "Get a Quote",
    heroSecondary: "View Products",
    metricCountries: "Target markets",
    metricCategories: "Product groups",
    metricQuoteValue: "1 day",
    metricQuote: "Quote turnaround",
    trustOne: "Trusted Turkish supplier network",
    trustTwo: "FOB, CIF and EXW delivery options",
    trustThree: "Transparent proforma preparation",
    trustFour: "Multilingual catalog support",
    productsKicker: "Catalog",
    productsTitle: "Featured product groups",
    supplierSearchKicker: "B2B Supply Search",
    supplierSearchTitle: "Find Products from TÃ¼rkiye",
    supplierSearchCopy: "Type a product name to see matching categories, brands, minimum order and loading notes.",
    supplierSearchLabel: "Buyer product search",
    supplierSearchPlaceholder: "Start searching products, brands or categories",
    supplierNoResultsTitle: "No matching supplier found",
    supplierNoResultsCopy: "Try another product name or send a custom request from the quote form.",
    supplierContactForm: "Contact",
    supplierMoqLabel: "Minimum order",
    supplierLoadingLabel: "Loading",
    supplierCategoryCta: "Product group",
    supplierContactCta: "Contact",
    partnersKicker: "Collaborations",
    partnersTitle: "Our strategic partners",
    partnerSiteCta: "Website",
    sampleCatalogCta: "Open Catalog",
    relatedCompanies: "Related companies",
    processKicker: "Export flow",
    processTitle: "A controlled path from inquiry to shipment",
    stepOneTitle: "Inquiry review",
    stepOneCopy: "Product, quantity, market and delivery needs are clarified.",
    stepTwoTitle: "Proforma setup",
    stepTwoCopy: "Pallet count and gross weight are calculated clearly.",
    stepThreeTitle: "Supply follow-up",
    stepThreeCopy: "Supplier, stock, packaging and loading details are coordinated.",
    stepFourTitle: "Logistics delivery",
    stepFourCopy: "Truck, container, documentation and shipment planning move together.",
    marketsKicker: "Target markets",
    marketsTitle: "Ready for nearby, northern and eastern markets from TÃ¼rkiye.",
    marketsCopy:
      "Sidya Global prepares offers for buyers across Europe, the Caucasus, the Black Sea region, Central Asia and the Middle East.",
    proformaKicker: "Proforma platform",
    proformaTitle: "Purchase proforma and loading calculator",
    proformaCopy: "Select a product line, enter pallet quantity and see total pallet and weight values instantly.",
    proformaBuyer: "Buyer company",
    proformaProduct: "Product line",
    proformaPallets: "Pallet quantity",
    proformaOrderTitle: "Create a proforma order",
    proformaOrderCopy: "Open the product selector, search by brand or product name, enter carton quantity and add items to the proforma total.",
    proformaOpenProducts: "Create Proforma Order",
    proformaSearchLabel: "Search product",
    proformaNoSearchResults: "No catalog product matches this search.",
    proformaTransportTitle: "Select loading type",
    proformaTransportTruck: "TIR",
    proformaTransportContainer: "Container",
    proformaContainerRouteTitle: "Container delivery route",
    proformaContainerRoad: "By TIR / road",
    proformaContainerSea: "By ship / sea",
    proformaAddLine: "Add",
    proformaCartonQty: "Carton qty",
    proformaUnitsPerCarton: "Units / carton",
    proformaCartonsPerPallet: "Cartons / pallet",
    proformaKgPerCarton: "Kg / carton",
    proformaSummaryTitle: "Proforma total",
    proformaEmpty: "No product added yet.",
    proformaTotalCartons: "Total cartons",
    proformaTotalPallets: "Estimated pallets",
    proformaTotalWeight: "Estimated gross weight",
    proformaExcelCta: "Download Excel",
    proformaMailCta: "Send by Mail",
    proformaWhatsappCta: "Send by WhatsApp",
    proformaTelegramCta: "Send by Telegram",
    proformaShareReady: "Choose the target application from the share panel. The Excel file is attached.",
    proformaShareFallback: "The Excel file was downloaded. Your selected application is opening; attach the downloaded file if your browser cannot share files.",
    proformaShareCancelled: "Sharing was cancelled.",
    proformaQuoteEmpty: "Please add at least one product to the proforma list.",
    proformaBackToCategory: "Back to category products",
    catalogProformaKicker: "Category proforma",
    catalogProformaTitle: "Create proforma without registration",
    catalogProformaCopy: "Select products from this category, enter carton quantity and add them to your proforma total.",
    catalogProformaSearch: "Search in this category",
    catalogProformaEmpty: "No products are loaded for this category yet. You can add the related company as a category request.",
    catalogProformaViewSummary: "View proforma total",
    catalogProformaAdded: "Added to proforma total.",
    catalogProformaPartnerType: "Category request",
    b2bKicker: "B2B export portal",
    b2bTitle: "Buyer registration, document intake and export compliance flow.",
    b2bCopy: "Register buyers, collect required documents and follow the export path from proforma to customs clearance.",
    b2bEntryTitle: "Register as a buyer",
    b2bEntryCopy: "Open the buyer registration screen to enter company details, tax information and upload required documents.",
    b2bRegisterCta: "Buyer Register",
    guestProformaTitle: "Create proforma without registration",
    guestProformaCopy: "Open the proforma order screen directly, select products and calculate carton, pallet and kg totals.",
    guestProformaCta: "Create Proforma Order",
    b2bRegisterTitle: "Buyer registration",
    b2bRegisterCopy: "Sign in if you already have an account, or create a new buyer account from the registration form below.",
    b2bNewRegistrationTitle: "New buyer registration",
    b2bPasswordHint: "Complete the company form. Buyer registration does not create a panel login account.",
    b2bCompany: "Company legal name",
    b2bContact: "Authorized contact",
    b2bEmail: "Business email",
    b2bUsername: "Username",
    b2bPassword: "Password",
    b2bCountry: "Destination country",
    b2bTax: "Tax / registration number",
    b2bIncoterm: "Preferred Incoterm",
    b2bDocuments: "Upload company and import documents",
    b2bNoFiles: "No files selected.",
    b2bFilesSelected: "files selected",
    b2bNotes: "Products, market notes and customs requirements",
    b2bSubmit: "Create buyer account",
    b2bReady: "Buyer account was created and saved.",
    b2bAuthTitle: "Sign in or register",
    b2bAuthCopy: "Buyer registration creates a customer record only. The operations panel uses one separate administrator account.",
    b2bEmailRegisterHint: "New buyers are not created as system users.",
    b2bAuthEmail: "Account email",
    b2bAuthPassword: "Password",
    b2bSignUp: "Register",
    b2bSignIn: "Sign in",
    b2bSignOut: "Sign out",
    b2bAuthNotReady: "B2B login is not connected yet.",
    b2bAuthEmailMode: "B2B login is not connected yet. Send buyer registration below; we will activate login after the account system is connected.",
    b2bAuthEmailCopied: "Email added to the B2B form.",
    b2bAuthEmailRequired: "Enter an email first.",
    b2bAuthFormReady: "Complete the B2B form and send the request.",
    b2bAuthLoginRequired: "Enter email and password.",
    b2bAuthLoginStarted: "Signing in...",
    b2bAuthLoginDone: "Signed in. You can now open the order screen.",
    b2bAuthLoginFailed: "Login failed. Check the email/password or account activation status.",
    b2bAuthSignupStarted: "Creating buyer account...",
    b2bAuthSignupDone: "Buyer account created.",
    b2bAuthTimeout: "Account service did not respond. Please try again in a moment.",
    b2bAuthSelectFiles: "Select the company/import documents to attach.",
    b2bSignedIn: "Signed in",
    b2bSignedOut: "Signed out",
    b2bCheckEmail: "Registration started. Check your email if confirmation is enabled.",
    b2bUploadLoginRequired: "Sign in before uploading documents.",
    b2bUploadStarted: "Uploading documents...",
    b2bUploadDone: "B2B request saved. Documents uploaded.",
    b2bRegisteredOpenProforma: "Buyer account created. You can now sign in and open the order screen.",
    b2bOpenOrderScreen: "Open order screen",
    b2bBackendFallback: "Opening email draft.",
    b2bServerSubmit: "Creating buyer account and saving documents...",
    b2bSaving: "Saving...",
    b2bUploadingDocuments: "Uploading documents securely...",
    b2bSavingRequest: "Saving company registration...",
    b2bServerMissing: "B2B registration backend is not active yet. Check Vercel environment variables.",
    b2bRegistrationLoginReady: "Buyer account created. Sign in with your email and password.",
    customerDashboardKicker: "Customer portal",
    customerDashboardTitle: "Your Sidya Global account",
    customerDashboardCopy: "Review your previous proforma orders or create a new order.",
    customerHistoryKicker: "Order history",
    customerHistoryTitle: "Previous orders",
    customerHistoryEmpty: "No previous order has been recorded yet.",
    customerNewOrder: "Create a new order",
    customerOrderItems: "items",
    customerOrderCartons: "cartons",
    customerOrderPallets: "pallets",
    customerOrderDownloaded: "Excel downloaded",
    customerOrderWeight: "gross weight",
    customerOrderDetails: "View order details",
    customerOrderRepeat: "Repeat order",
    customerOrderRepeatUnavailable: "This older order does not contain enough line data to repeat.",
    customerOrderDateTotal: "Proforma total",
    customerSignOut: "Sign out",
    b2bChecklistTitle: "Core export document checklist",
    b2bDocBuyer: "Buyer company registry, tax certificate and authorized signatory",
    b2bDocProduct: "Product list, HS code, quantity, pallet and weight confirmation",
    b2bDocCommercial: "Proforma invoice, sales confirmation and payment term",
    b2bDocShipment: "Commercial invoice, packing list and transport document",
    b2bDocOrigin: "Certificate of origin, A.TR, EUR.1 or market-specific origin document",
    b2bDocCustoms: "Customs declaration, conformity documents and product certificates if required",
    b2bStepOne: "Buyer verification",
    b2bStepOneCopy: "Company identity, tax registration, authorization and destination market are checked before a standing customer file is opened.",
    b2bStepTwo: "Product and HS code review",
    b2bStepTwoCopy: "Products are matched with HS codes, certificates, restrictions and country-specific import requirements.",
    b2bStepThree: "Proforma and payment approval",
    b2bStepThreeCopy: "Incoterm, currency, payment term, pallet plan, loading weight and delivery responsibility are confirmed.",
    b2bStepFour: "Customs and origin file",
    b2bStepFourCopy: "Invoice, packing list, transport document, origin certificate and required conformity documents are prepared in sequence.",
    customsKicker: "Customs platform",
    customsTitle: "End-to-end export customs control desk",
    customsCopy: "Plan the export file from buyer verification to customs declaration, shipment handover and archive closure.",
    customsPlannerTitle: "Export route planner",
    customsPlannerCopy: "Select the destination, transport type and Incoterm to see the operational customs file.",
    customsDestination: "Destination market",
    customsMarketEu: "European Union",
    customsMarketCaucasus: "Caucasus",
    customsMarketMiddleEast: "Middle East",
    customsMarketCentralAsia: "Central Asia",
    customsTransport: "Transport mode",
    customsTransportTruck: "Truck",
    customsTransportContainer: "Container",
    customsTransportAir: "Air cargo",
    customsIncoterm: "Incoterm",
    customsProduct: "Product risk group",
    customsProductStandard: "Standard commercial goods",
    customsProductCleaning: "Cleaning products",
    customsProductFood: "Food products",
    customsProductHomeware: "Home and living",
    customsProductIndustrial: "Industrial supplies",
    customsProductCosmetics: "Cosmetics / hygiene",
    customsProductMedical: "Medical products",
    customsProductAutomotive: "Automotive",
    customsProductHardware: "Construction and hardware",
    customsStatusLabel: "File status",
    customsStatusReady: "Ready for document review",
    customsStatusReadyCopy: "Commercial documents, origin documents and shipment instructions should be checked before declaration.",
    customsMailCta: "Send customs file request",
    customsWhatsappCta: "Send by WhatsApp",
    customsDocsTitle: "Required document pack",
    customsActionTitle: "Action checklist",
    customsRiskTitle: "Risk notes",
    customsCoreDocsKicker: "Document checklist",
    customsCoreDocsTitle: "Required export customs documents",
    customsCoreDocsCopy: "Keep the commercial, origin, product and transport files together before the declaration stage.",
    custoë­¸ŞÚ$z{-®éÜj×Fö7VÖVçE÷F‡3¢Fö7VÖVçEF‡2ÀĞ¢Ó°Ğ¢6öç7B²W'&÷"ÒÒv—B6Æ–VçBæg&öÒ‚&#&%ööæ&ö&F–æu÷&WVW7G2"’æ–ç6W'B‡–ÆöB“°Ğ¢–b†W'&÷"’F‡&÷rW'&÷#°Ğ§Ó°Ğ Ğ¦6öç7BvWD#$$WF…fÇVW2Ò‚’Óâ‡°Ğ¢VÖ–Ã¢Fö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$WF„VÖ–Â"“òçfÇVRçG&–Ò‚’ÇÂ""ÀĞ¢77v÷&C¢Fö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$WF…77v÷&B"“òçfÇVRÇÂ""ÀĞ§Ò“°Ğ Ğ¦6öç7Bfö7W4#$$f÷&ÒÒ‚’Óâ°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$f÷&Ò"“òç67&öÆÄ–çFõf–Wr‡²&V†f–÷#¢'6Öö÷F‚"Â&Æö6³¢'7F'B"Ò“°Ğ§Ó°Ğ Ğ¦6öç7B6WD#$%&Vv—7G&F–öåæVÅf—6–&ÆRÒ†—5f—6–&ÆR’Óâ°Ğ¢6öç7BæVÂÒFö7VÖVçBçVW'•6VÆV7F÷"‚"6#&%&Vv—7G&F–öåæVÂ"“°Ğ¢–b‡æVÂ’æVÂæ†–FFVâÒ—5f—6–&ÆS°Ğ§Ó°Ğ Ğ¦6öç7B6÷”#$$VÖ–ÅFôf÷&ÒÒ‚’Óâ°Ğ¢6öç7B²VÖ–ÂÒÒvWD#$$WF…fÇVW2‚“°Ğ¢6öç7BF&vWBÒFö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$f÷&Ò¶æÖSÒvVÖ–ÂuÒ"“°Ğ¢–b†VÖ–ÂbbF&vWB’F&vWBçfÇVRÒVÖ–Ã°Ğ¢fö7W4#$$f÷&Ò‚“°Ğ¢6WD#$$WF…7FGW2†VÖ–ÂòB‚&#&$WF„VÖ–Ä6÷–VB"’¢B‚&#&$WF„VÖ–Å&WV—&VB"’“°Ğ§Ó°Ğ Ğ¦6öç7B6–vä–ä#$$7W7FöÖW"Ò7–æ2‚’Óâ°Ğ¢6öç7B6Æ–VçBÒvWE7W&6T6Æ–VçB‚“°Ğ¢6öç7B²VÖ–ÂÂ77v÷&BÒÒvWD#$$WF…fÇVW2‚“°Ğ¢–b‚VÖ–ÂÇÂ77v÷&B’°Ğ¢6WD#$$WF…7FGW2‡B‚&#&$WF„Æöv–å&WV—&VB"’“°Ğ¢&WGW&ã°Ğ¢ĞĞ¢–b‚6Æ–VçB’°Ğ¢6WD#$$WF…7FGW2‡B‚&#&$WF„VÖ–ÄÖöFR"’“°Ğ¢&WGW&ã°Ğ¢ĞĞ¢G'’°Ğ¢6WD#$$WF…7FGW2‡B‚&#&$WF„Æöv–å7F'FVB"’“°Ğ¢6öç7B²FFÂW'&÷"ÒÒv—Bv—F…F–ÖV÷WB†6Æ–VçBæWF‚ç6–vä–åv—F…77v÷&B‡²VÖ–ÂÂ77v÷&BÒ’ÂB‚&#&$WF…F–ÖV÷WB"’“°Ğ¢–b†W'&÷"’F‡&÷rW'&÷#°Ğ¢6WD#$$WF…7FGW2‡B‚&#&$WF„Æöv–äFöæR"’“°Ğ¢7F—fT#$%6W76–öâÒFFç6W76–öã°Ğ¢6Æ÷6T#$$ÖöFÂ‚“°Ğ¢÷Vä7W7FöÖW$F6†&ö&B†FFç6W76–öâ“°Ğ¢Ò6F6‚†W'&÷"’°Ğ¢6WD#$$WF…7FGW2†W'&÷"æÖW76vRÇÂB‚&#&$WF„Æöv–äf–ÆVB"’“°Ğ¢ĞĞ§Ó°Ğ Ğ¦6öç7B6–vä÷WD#$$7W7FöÖW"Ò7–æ2‚’Óâ°Ğ¢6öç7B6Æ–VçBÒvWE7W&6T6Æ–VçB‚“°Ğ¢–b†6Æ–VçB’v—B6Æ–VçBæWF‚ç6–vä÷WB‚“°Ğ¢7F—fT#$%6W76–öâÒçVÆÃ°Ğ¢v—B&Vg&W6„#$%6W76–öâ‚“°Ğ§Ó°Ğ Ğ¦6öç7B6WE&öf÷&ÖG&ç7÷'BÒ‡G&ç7÷'BÂ&÷WFRÒ6VÆV7FVD6öçF–æW%&÷WFR’Óâ°Ğ¢6VÆV7FVE&öf÷&ÖG&ç7÷'BÒG&ç7÷'BÓÓÒ&6öçF–æW""ò&6öçF–æW""¢'G'V6²#°Ğ¢6VÆV7FVD6öçF–æW%&÷WFRÒ&÷WFRÓÓÒ'6V"ò'6V"¢'&öB#°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚v–çWE¶æÖSÒ'&öf÷&ÖG&ç7÷'B%Òr’æf÷$V6‚‚†–çWB’Óâ°Ğ¢–çWBæ6†V6¶VBÒ–çWBçfÇVRÓÓÒ6VÆV7FVE&öf÷&ÖG&ç7÷'C°Ğ¢Ò“°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚v–çWE¶æÖSÒ'&öf÷&Ö6öçF–æW%&÷WFR%Òr’æf÷$V6‚‚†–çWB’Óâ°Ğ¢–çWBæ6†V6¶VBÒ–çWBçfÇVRÓÓÒ6VÆV7FVD6öçF–æW%&÷WFS°Ğ¢Ò“°Ğ¢&VæFW%&öf÷&Ö÷&FW"‚“°Ğ§Ó°Ğ Ğ¦6öç7B&WVD7W7FöÖW$÷&FW"Ò†÷&FW$–B’Óâ°Ğ¢6öç7B÷&FW"ÒvWD7W7FöÖW$÷&FW$†—7F÷'’†7F—fT#$%6W76–öâ’æf–æB‚†—FVÒ’Óâ—FVÒæ–BÓÓÒ÷&FW$–B“°Ğ¢–b‚÷&FW#òæ—FV×3òæÆVæwF‚’°Ğ¢ÆW'B‡B‚&7W7FöÖW$÷&FW%&WVEVæf–Æ&ÆR"’“°Ğ¢&WGW&ã°Ğ¢ĞĞ Ğ¢&öf÷&Ö÷&FW"æ6ÆV"‚“°Ğ¢÷&FW"æ—FV×2æf÷$V6‚‚†—FVÒ’Óâ°Ğ¢6öç7B&öGV7BĞĞ¢&öGV7D6FÆöræf–æB‚†VçG'’’ÓâVçG'’æ–BÓÓÒ—FVÒç&öGV7D–B’ÇÀĞ¢&öGV7D6FÆöræf–æB‚†VçG'’’Óâ—FVÒæ&&6öFRbbVçG'’æ&&6öFRÓÓÒ—FVÒæ&&6öFR’ÇÀĞ¢&öGV7D6FÆöræf–æB€Ğ¢†VçG'’’ÓàĞ¢æ÷&ÖÆ—¦T6FÆötæÖR†VçG'’æ'&æB’ÓÓÒæ÷&ÖÆ—¦T6FÆötæÖR†—FVÒæ'&æB’b`Ğ¢æ÷&ÖÆ—¦T6FÆötæÖR†vWE&öGV7DæÖR†VçG'’’’ÓÓÒæ÷&ÖÆ—¦T6FÆötæÖR†—FVÒç&öGV7B’ÀĞ¢“°Ğ¢–b‡&öGV7B’&öf÷&Ö÷&FW"ç6WB‡&öGV7Bæ–BÂÖF‚æÖ‚„çVÖ&W"†—FVÒæ6'Föç2’ÇÂÂ’“°Ğ¢Ò“°Ğ Ğ¢6WE&öf÷&ÖG&ç7÷'B†÷&FW"çG&ç7÷'BÂ÷&FW"æ6öçF–æW%&÷WFR“°Ğ¢6Æ÷6T7W7FöÖW$F6†&ö&B‚“°Ğ¢÷VäÖ–å&öf÷&ÖæVÂ‡²fö7W57VÖÖ'“¢G'VRÒ“°Ğ§Ó°Ğ Ğ¦6öç7B#&$ÖöFÂÒFö7VÖVçBçVW'•6VÆV7F÷"‚"6#&%&Vv—7G&F–öäÖöFÂ"“°Ğ¦6öç7B7W7FöÖW$F6†&ö&DÖöFÂÒFö7VÖVçBçVW'•6VÆV7F÷"‚"67W7FöÖW$F6†&ö&DÖöFÂ"“°Ğ¦6öç7BÆöv—7F–74ÖöFÂÒFö7VÖVçBçVW'•6VÆV7F÷"‚"6Æöv—7F–74ÖöFÂ"“°Ğ¦6öç7B÷Vä#$$ÖöFÂÒ‚’Óâ°Ğ¢–b‚#&$ÖöFÂ’&WGW&ã°Ğ¢6WD#$%&Vv—7G&F–öåæVÅf—6–&ÆR†fÇ6R“°Ğ¢#&$ÖöFÂæ†–FFVâÒfÇ6S°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7BæFB‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ¢6WEF–ÖV÷WB‚‚’ÓâFö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$WF„VÖ–Â"“òæfö7W2‚’Â“°Ğ§Ó°Ğ Ğ¦6öç7B6Æ÷6T#$$ÖöFÂÒ‚’Óâ°Ğ¢–b‚#&$ÖöFÂ’&WGW&ã°Ğ¢6WD#$%&Vv—7G&F–öåæVÅf—6–&ÆR†fÇ6R“°Ğ¢#&$ÖöFÂæ†–FFVâÒG'VS°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7Bç&VÖ÷fR‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ§Ó°Ğ Ğ¦6öç7B÷Vä7W7FöÖW$F6†&ö&BÒ‡6W76–öâÒ7F—fT#$%6W76–öâ’Óâ°Ğ¢–b‚7W7FöÖW$F6†&ö&DÖöFÂÇÂ6W76–öãòçW6W"’&WGW&ã°Ğ¢7F—fT#$%6W76–öâÒ6W76–öã°Ğ¢7W7FöÖW$F6†&ö&DÖöFÂæ†–FFVâÒfÇ6S°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7BæFB‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ¢&VæFW$7W7FöÖW$÷&FW$†—7F÷'’‡6W76–öâ“°Ğ§Ó°Ğ Ğ¦6öç7B6Æ÷6T7W7FöÖW$F6†&ö&BÒ‚’Óâ°Ğ¢–b‚7W7FöÖW$F6†&ö&DÖöFÂ’&WGW&ã°Ğ¢7W7FöÖW$F6†&ö&DÖöFÂæ†–FFVâÒG'VS°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7Bç&VÖ÷fR‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ§Ó°Ğ Ğ¦6öç7B÷VäÆöv—7F–74ÖöFÂÒ‚’Óâ°Ğ¢–b‚Æöv—7F–74ÖöFÂ’&WGW&ã°Ğ¢Æöv—7F–74ÖöFÂæ†–FFVâÒfÇ6S°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7BæFB‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ¢&VæFW$Æöv—7F–746VçFW"‚“°Ğ¢fWF6„Æöv—7F–757FGW2‚“°Ğ§Ó°Ğ Ğ¦6öç7B6Æ÷6TÆöv—7F–74ÖöFÂÒ‚’Óâ°Ğ¢–b‚Æöv—7F–74ÖöFÂ’&WGW&ã°Ğ¢Æöv—7F–74ÖöFÂæ†–FFVâÒG'VS°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7Bç&VÖ÷fR‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ§Ó°Ğ Ğ¦6öç7B7F—fFTÆöv—7F–75F"Ò‡F$æÖR’Óâ°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖÆöv—7F–72×F%Ò"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæ6Æ74Æ—7BçFövvÆR‚&—2Ö7F—fR"Â'WGFöâæFF6WBæÆöv—7F–75F"ÓÓÒF$æÖR“°Ğ¢Ò“°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖÆöv—7F–72×æVÅÒ"’æf÷$V6‚‚‡æVÂ’Óâ°Ğ¢6öç7B—47F—fRÒæVÂæFF6WBæÆöv—7F–75æVÂÓÓÒF$æÖS°Ğ¢æVÂæ†–FFVâÒ—47F—fS°Ğ¢æVÂæ6Æ74Æ—7BçFövvÆR‚&—2Ö7F—fR"Â—47F—fR“°Ğ¢Ò“°Ğ§Ó°Ğ Ğ¦6öç7B÷Vä7W7FöÖW%&öf÷&ÖæVÂÒ‚’Óâ°Ğ¢6Æ÷6T7W7FöÖW$F6†&ö&B‚“°Ğ¢÷VäÖ–å&öf÷&ÖæVÂ‚“°Ğ§Ó°Ğ Ğ¦6öç7B÷VäÖ–å&öf÷&ÖæVÂÒ†÷F–öç2Ò·Ò’Óâ°Ğ¢6öç7B&öf÷&Ö67&VVâÒFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö"“°Ğ¢–b‡&öf÷&Ö67&VVâ’°Ğ¢&öf÷&Ö67&VVâæ†–FFVâÒfÇ6S°Ğ¢&öf÷&Ö67&VVâæ6Æ74Æ—7BçFövvÆR‚&—2×7VÖÖ'’Öfö7W2"Â&ööÆVâ†÷F–öç2æfö7W57VÖÖ'’’“°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7BæFB‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ¢ĞĞ¢6öç7B&6´'WGFöâÒFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö&6µFô6FVv÷'’"“°Ğ¢–b†&6´'WGFöâ’&6´'WGFöâæ†–FFVâÒ&WGW&ä6FÆöu&öf÷&Ö6FVv÷'“°Ğ¢6öç7BæVÂÒFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö&öGV7EæVÂ"“°Ğ¢–b‡æVÃòæ†4GG&–'WFR‚&†–FFVâ"’’æVÂç&VÖ÷fTGG&–'WFR‚&†–FFVâ"“°Ğ¢–b„ö&¦V7Bç&÷F÷G—Ræ†4÷vå&÷W'G’æ6ÆÂ†÷F–öç2Â'6V&6…VW'’"’’°Ğ¢6öç7B6V&6‚ÒFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö6V&6‚"“°Ğ¢–b‡6V&6‚’6V&6‚çfÇVRÒ÷F–öç2ç6V&6…VW'’ÇÂ"#°Ğ¢ĞĞ¢&VæFW%&öf÷&Ö&öGV7G2‚“°Ğ¢6WEF–ÖV÷WB‚‚’Óâ°Ğ¢–b†÷F–öç2æfö7W57VÖÖ'’’°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö÷&FW%7VÖÖ'’"“òç67&öÆÄ–çFõf–Wr‡²&V†f–÷#¢'6Öö÷F‚"Â&Æö6³¢'7F'B"Ò“°Ğ¢&WGW&ã°Ğ¢ĞĞ¢Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö6V&6‚"“òæfö7W2‚“°Ğ¢ÒÂ#S“°Ğ§Ó°Ğ Ğ¦6öç7B6Æ÷6TÖ–å&öf÷&ÖæVÂÒ‚’Óâ°Ğ¢6öç7B&öf÷&Ö67&VVâÒFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö"“°Ğ¢–b‡&öf÷&Ö67&VVâ’&öf÷&Ö67&VVâæ†–FFVâÒG'VS°Ğ¢&öf÷&Ö67&VVãòæ6Æ74Æ—7Bç&VÖ÷fR‚&—2×7VÖÖ'’Öfö7W2"“°Ğ¢Fö7VÖVçBæ&öG’æ6Æ74Æ—7Bç&VÖ÷fR‚&—2ÖÖöFÂÖ÷Vâ"“°Ğ§Ó°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷Vä#$%&Vv—7G&F–öâ"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â÷Vä#$$ÖöFÂ“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷Vä#$%÷'FÂ"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â7–æ2†WfVçB’Óâ°Ğ¢WfVçBç&WfVçDFVfVÇB‚“°Ğ¢6öç7B6W76–öâÒv—B&Vg&W6„#$%6W76–öâ‚“°Ğ¢–b‡6W76–öãòçW6W"’°Ğ¢÷Vä7W7FöÖW$F6†&ö&B‡6W76–öâ“°Ğ¢&WGW&ã°Ğ¢ĞĞ¢÷Vä#$$ÖöFÂ‚“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷VäÆöv—7F–746VçFW""“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢WfVçBç&WfVçDFVfVÇB‚“°Ğ¢÷VäÆöv—7F–74ÖöFÂ‚“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷Vä7W7Fö×46VçFW""“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢WfVçBç&WfVçDFVfVÇB‚“°Ğ¢÷Vä7W7Fö×4ÖöFÂ‚“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖ7W7Fö×2Ö÷VåÒ"’æf÷$V6‚‚†Æ–æ²’Óâ°Ğ¢Æ–æ²æFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢WfVçBç&WfVçDFVfVÇB‚“°Ğ¢÷Vä7W7Fö×4ÖöFÂ‚“°Ğ¢Ò“°Ğ§Ò“°Ğ¦Fö7VÖVçBæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢–b†WfVçBçF&vWBæ6Æ÷6W7B‚%¶FFÖ6Æ÷6RÖ7W7Fö×5Ò"’’6Æ÷6T7W7Fö×4ÖöFÂ‚“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖ6Æ÷6RÖÆöv—7F–75Ò"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â6Æ÷6TÆöv—7F–74ÖöFÂ“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖÆöv—7F–72×F%Ò"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ7F—fFTÆöv—7F–75F"†'WGFöâæFF6WBæÆöv—7F–75F"’“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷VäwVW7E&öf÷&Ö"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â÷VäÖ–å&öf÷&ÖæVÂ“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷Vä7W7FöÖW%&öf÷&Ö"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â÷Vä7W7FöÖW%&öf÷&ÖæVÂ“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"67W7FöÖW$F6†&ö&E6–vä÷WB"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â7–æ2‚’Óâ°Ğ¢v—B6–vä÷WD#$$7W7FöÖW"‚“°Ğ¢6Æ÷6T7W7FöÖW$F6†&ö&B‚“°Ğ¢÷Vä#$$ÖöFÂ‚“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"67W7FöÖW$÷&FW$†—7F÷'’"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢6öç7B'WGFöâÒWfVçBçF&vWBæ6Æ÷6W7B‚"æ7W7FöÖW"×&WVBÖ÷&FW""“°Ğ¢–b‚'WGFöâÇÂ'WGFöâæF—6&ÆVB’&WGW&ã°Ğ¢&WVD7W7FöÖW$÷&FW"†'WGFöâæFF6WBæ÷&FW$–B“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚v¶‡&VcÒ"7&öf÷&Ö%Òr’æf÷$V6‚‚†Æ–æ²’Óâ°Ğ¢Æ–æ²æFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢WfVçBç&WfVçDFVfVÇB‚“°Ğ¢÷VäÖ–å&öf÷&ÖæVÂ‚“°Ğ¢Ò“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖ6Æ÷6R×&öf÷&Ö×67&VVåÒ"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â6Æ÷6TÖ–å&öf÷&ÖæVÂ“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖ6Æ÷6RÖ#&%Ò"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â6Æ÷6T#$$ÖöFÂ“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖ6Æ÷6RÖ7W7FöÖW"ÖF6†&ö&EÒ"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â6Æ÷6T7W7FöÖW$F6†&ö&B“°Ğ§Ò“°Ğ¦Fö7VÖVçBæFDWfVçDÆ—7FVæW"‚&¶W–F÷vâ"Â†WfVçB’Óâ°Ğ¢–b†WfVçBæ¶W’ÓÓÒ$W66R"bb#&$ÖöFÂbb#&$ÖöFÂæ†–FFVâ’6Æ÷6T#$$ÖöFÂ‚“°Ğ¢–b†WfVçBæ¶W’ÓÓÒ$W66R"bb7W7FöÖW$F6†&ö&DÖöFÂbb7W7FöÖW$F6†&ö&DÖöFÂæ†–FFVâ’6Æ÷6T7W7FöÖW$F6†&ö&B‚“°Ğ¢–b†WfVçBæ¶W’ÓÓÒ$W66R"bb7W7Fö×4ÖöFÂbb7W7Fö×4ÖöFÂæ†–FFVâ’6Æ÷6T7W7Fö×4ÖöFÂ‚“°Ğ¢–b†WfVçBæ¶W’ÓÓÒ$W66R"bbÆöv—7F–74ÖöFÂbbÆöv—7F–74ÖöFÂæ†–FFVâ’6Æ÷6TÆöv—7F–74ÖöFÂ‚“°Ğ¢–b†WfVçBæ¶W’ÓÓÒ$W66R"bb6FÆöu&öf÷&ÖÖöFÂbb6FÆöu&öf÷&ÖÖöFÂæ†–FFVâ’6Æ÷6T6FÆöu&öf÷&ÖÖöFÂ‚“°Ğ¢–b†WfVçBæ¶W’ÓÓÒ$W66R"bbFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö"“òæ†–FFVâ’6Æ÷6TÖ–å&öf÷&ÖæVÂ‚“°Ğ§Ò“°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6#&%6–vä–â"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ°Ğ¢6–vä–ä#$$7W7FöÖW"‚“°Ğ§Ò“°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷Vä#$%&Vv—7FW$f÷&Ò"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ°Ğ¢6WD#$%&Vv—7G&F–öåæVÅf—6–&ÆR‡G'VR“°Ğ¢6÷”#$$VÖ–ÅFôf÷&Ò‚“°Ğ¢6WEF–ÖV÷WB‚‚’ÓâFö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$f÷&Ò¶æÖSÒv6ö×ç’uÒ"“òæfö7W2‚’Â#S“°Ğ§Ò“°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$Fö7VÖVçG2"“òæFDWfVçDÆ—7FVæW"‚&6†ævR"ÂWFFT#$$f–ÆU7VÖÖ'’“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚"67W7Fö×5ÆææW"6VÆV7B"’æf÷$V6‚‚‡6VÆV7B’Óâ°Ğ¢6VÆV7BæFDWfVçDÆ—7FVæW"‚&6†ævR"Â&VæFW$7W7Fö×4FW6²“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6#&$f÷&Ò"“òæFDWfVçDÆ—7FVæW"‚'7V&Ö—B"Â7–æ2†WfVçB’Óâ°Ğ¢WfVçBç&WfVçDFVfVÇB‚“°Ğ¢6öç7Bf÷&ÒÒWfVçBæ7W'&VçEF&vWC°Ğ¢6öç7B7FGW2ÒFö7VÖVçBçVW'•6VÆV7F÷"‚"6#&%7FGW2"“°Ğ¢6öç7B7V&Ö—D'WGFöâÒf÷&ÓòçVW'•6VÆV7F÷"‚v'WGFöå·G—SÒ'7V&Ö—B%Òr“°Ğ¢G'’°Ğ¢–b‡7V&Ö—D'WGFöâ’°Ğ¢7V&Ö—D'WGFöâæF—6&ÆVBÒG'VS°Ğ¢7V&Ö—D'WGFöâçFW‡D6öçFVçBÒB‚&#&%6f–ær"“°Ğ¢ĞĞ¢–b‡7FGW2’7FGW2çFW‡D6öçFVçBÒB‚&#&%6W'fW%7V&Ö—B"“°Ğ¢6öç7B&W7VÇBÒv—B7V&Ö—D#$%&Vv—7G&F–öâ†f÷&Ò“°Ğ¢–b‚&W7VÇBæö²’F‡&÷ræWrW'&÷"‡B‚&#&%6W'fW$Ö—76–ær"’“°Ğ Ğ¢–b‡7FGW2’7FGW2çFW‡D6öçFVçBÒB‚&#&%&Vv—7FW&VD÷Vå&öf÷&Ö"“°Ğ¢f÷&Óòç&W6WB‚“°Ğ¢WFFT#$$f–ÆU7VÖÖ'’‚“°Ğ¢6WD#$%&Vv—7G&F–öåæVÅf—6–&ÆR†fÇ6R“°Ğ¢Ò6F6‚†W'&÷"’°Ğ¢–b‡7FGW2’7FGW2çFW‡D6öçFVçBÒW'&÷"æÖW76vRÇÂB‚&f÷&ÔW'&÷""“°Ğ¢Òf–æÆÇ’°Ğ¢–b‡7V&Ö—D'WGFöâ’°Ğ¢7V&Ö—D'WGFöâæF—6&ÆVBÒfÇ6S°Ğ¢7V&Ö—D'WGFöâçFW‡D6öçFVçBÒB‚&#&%7V&Ö—B"“°Ğ¢ĞĞ¢ĞĞ§Ò“°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚%¶FFÖ6Æ÷6RÖ6FÆör×&öf÷&ÖÒ"’æf÷$V6‚‚†'WGFöâ’Óâ°Ğ¢'WGFöâæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â6Æ÷6T6FÆöu&öf÷&ÖÖöFÂ“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"66FÆöu&öf÷&Ö6V&6‚"“òæFDWfVçDÆ—7FVæW"‚&–çWB"Â&VæFW$6FÆöu&öf÷&Ö&öGV7G2“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"66FÆöu&öf÷&ÖÆ—7B"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢6öç7B'WGFöâÒWfVçBçF&vWBæ6Æ÷6W7B‚"æ6FÆör×&öf÷&ÖÖFB"“°Ğ¢–b‚'WGFöâ’&WGW&ã°Ğ¢6öç7BVçF—G”–çWBÒFö7VÖVçBçVW'•6VÆV7F÷"†¶FFÖ6FÆör×G’Öf÷#Ò"G¶'WGFöâæFF6WBç&öGV7D–GÒ%Ö“°Ğ¢FE&öf÷&ÖÆ–æUv—F…VçF—G’†'WGFöâæFF6WBç&öGV7D–BÂçVÖ&W"‡VçF—G”–çWCòçfÇVR’ÇÂ“°Ğ¢6öç7B7FGW2ÒFö7VÖVçBçVW'•6VÆV7F÷"‚"66FÆöu&öf÷&Ö7FGW2"“°Ğ¢–b‡7FGW2’7FGW2çFW‡D6öçFVçBÒB‚&6FÆöu&öf÷&ÖFFVB"“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"66FÆöu&öf÷&Ö7VÖÖ'’"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ°Ğ¢&WGW&ä6FÆöu&öf÷&Ö6FVv÷'’Ò7F—fT6FÆöu&öf÷&Ö6FVv÷'“°Ğ¢&WGW&ä6FÆöu&öf÷&ÖF—FÆRÒFö7VÖVçBçVW'•6VÆV7F÷"‚"66FÆör×&öf÷&Ö×F—FÆR"“òçFW‡D6öçFVçBÇÂ"#°Ğ¢6Æ÷6T6FÆöu&öf÷&ÖÖöFÂ‚“°Ğ¢÷VäÖ–å&öf÷&ÖæVÂ‡²fö7W57VÖÖ'“¢G'VRÒ“°Ğ§Ò“°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö&6µFô6FVv÷'’"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ°Ğ¢6öç7B6FVv÷'”–BÒ&WGW&ä6FÆöu&öf÷&Ö6FVv÷'“°Ğ¢6öç7BF—FÆRÒ&WGW&ä6FÆöu&öf÷&ÖF—FÆS°Ğ¢6Æ÷6TÖ–å&öf÷&ÖæVÂ‚“°Ğ¢–b†6FVv÷'”–B’÷Vä6FÆöu&öf÷&ÖÖöFÂ†6FVv÷'”–BÂF—FÆRÇÂvWD6FVv÷'•F—FÆR†6FVv÷'”–B’“°Ğ§Ò“°Ğ Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6÷Vå&öf÷&Ö&öGV7G2"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ°Ğ¢6öç7BæVÂÒFö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö&öGV7EæVÂ"“°Ğ¢æVÃòçFövvÆTGG&–'WFR‚&†–FFVâ"“°Ğ¢–b‚æVÃòæ†4GG&–'WFR‚&†–FFVâ"’’°Ğ¢Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö6V&6‚"“òæfö7W2‚“°Ğ¢ĞĞ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö6V&6‚"“òæFDWfVçDÆ—7FVæW"‚&–çWB"Â&VæFW%&öf÷&Ö&öGV7G2“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚v–çWE¶æÖSÒ'&öf÷&ÖG&ç7÷'B%Òr’æf÷$V6‚‚†–çWB’Óâ°Ğ¢–çWBæFDWfVçDÆ—7FVæW"‚&6†ævR"Â‚’Óâ6WE&öf÷&ÖG&ç7÷'B†–çWBçfÇVR’“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷$ÆÂ‚v–çWE¶æÖSÒ'&öf÷&Ö6öçF–æW%&÷WFR%Òr’æf÷$V6‚‚†–çWB’Óâ°Ğ¢–çWBæFDWfVçDÆ—7FVæW"‚&6†ævR"Â‚’Óâ6WE&öf÷&ÖG&ç7÷'B‚&6öçF–æW""Â–çWBçfÇVR’“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö&öGV7DÆ—7B"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢6öç7B'WGFöâÒWfVçBçF&vWBæ6Æ÷6W7B‚"ç&öf÷&ÖÖFBÖ'WGFöâ"“°Ğ¢–b‚'WGFöâ’&WGW&ã°Ğ¢FE&öf÷&ÖÆ–æR†'WGFöâæFF6WBç&öGV7D–B“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"7&öf÷&Ö÷&FW$Æ–æW2"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â†WfVçB’Óâ°Ğ¢6öç7BVçF—G”'WGFöâÒWfVçBçF&vWBæ6Æ÷6W7B‚"ç&öf÷&Ö×G’Ö'WGFöâ"“°Ğ¢–b‡VçF—G”'WGFöâ’°Ğ¢WFFU&öf÷&ÖVçF—G’‡VçF—G”'WGFöâæFF6WBç&öGV7D–BÂçVÖ&W"‡VçF—G”'WGFöâæFF6WBæFVÇF’“°Ğ¢&WGW&ã°Ğ¢ĞĞ¢6öç7B&VÖ÷fT'WGFöâÒWfVçBçF&vWBæ6Æ÷6W7B‚"ç&öf÷&Ö×&VÖ÷fRÖ'WGFöâ"“°Ğ¢–b‚&VÖ÷fT'WGFöâ’&WGW&ã°Ğ¢&öf÷&Ö÷&FW"æFVÆWFR‡&VÖ÷fT'WGFöâæFF6WBç&öGV7D–B“°Ğ¢&VæFW%&öf÷&Ö÷&FW"‚“°Ğ§Ò“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6F÷væÆöE&öf÷&ÖW†6VÂ"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"ÂF÷væÆöE&öf÷&ÖW†6VÂ“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"6Ö–Å&öf÷&Ö"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â6VæE&öf÷&ÖÖ–Â“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"7v†G6&öf÷&Ö"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ6†&U&öf÷&Ö‚'v†G6"’“°Ğ¦Fö7VÖVçBçVW'•6VÆV7F÷"‚"7FVÆVw&Õ&öf÷&Ö"“òæFDWfVçDÆ—7FVæW"‚&6Æ–6²"Â‚’Óâ6†&U&öf÷&Ö‚'FVÆVw&Ò"’“°Ğ§G&ç6ÆFUvR‚“°Ğ§6WGWG&6¶–ær‚“°Ğ§&Vg&W6„#$%6W76–öâ‚“°Ğ¦fWF6„Æöv—7F–757FGW2‚“°Ğ¦ÆöDW†6†ævU&FW2‚“°Ğ¦ÆöEV&Æ—6†VD6FÆöu&–6W2‚“°Ğ